import { ArrowDown, ArrowUp, Camera, ChevronRight, ImagePlus, Plus, Trash2 } from 'lucide-react'
import type { AlbumEntry, MomentProject } from '../lib/project-store'
import { newAlbumEntry, readLocalPicture } from '../lib/album-project'
import { WechatText } from './WechatText'

export function AlbumComposer({entries,onChange,onToast}:{entries:AlbumEntry[];onChange:(v:AlbumEntry[])=>void;onToast:(s:string)=>void}) {
  const update=(id:string,v:Partial<AlbumEntry>)=>onChange(entries.map(e=>e.id===id?{...e,...v}:e))
  const move=(i:number,d:number)=>{const v=[...entries];[v[i],v[i+d]]=[v[i+d],v[i]];onChange(v)}
  return <div className="album-composer"><div className="group-editor-heading"><strong>相册内容（{entries.length} 条）</strong><button disabled={entries.length>=200} className="btn btn-outline btn-sm" onClick={()=>onChange([...entries,newAlbumEntry()])}><Plus size={14}/>添加条目</button></div><p className="form-help">视频使用封面图片和播放图标。勾选置顶后出现在封面下方的置顶栏。</p>{entries.map((entry,i)=><div className="album-entry-editor" id={'album-entry-'+entry.id} key={entry.id}><div className="album-entry-heading"><strong>第 {i+1} 条</strong><label className="me-check"><input type="checkbox" checked={entry.pinned} onChange={e=>update(entry.id,{pinned:e.target.checked})}/>置顶</label><button title="上移条目" disabled={!i} className="btn btn-ghost btn-sm" onClick={()=>move(i,-1)}><ArrowUp size={14}/></button><button title="下移条目" disabled={i===entries.length-1} className="btn btn-ghost btn-sm" onClick={()=>move(i,1)}><ArrowDown size={14}/></button><button title="删除条目" className="btn btn-ghost btn-sm" onClick={()=>onChange(entries.filter(e=>e.id!==entry.id))}><Trash2 size={14}/></button></div><div className="me-row"><input className="me-input" aria-label="相册日期" placeholder="今天／昨天／01" value={entry.date} onChange={e=>update(entry.id,{date:e.target.value})}/><input className="me-input" aria-label="相册月份" placeholder="月份（如 8月，可留空）" value={entry.month} onChange={e=>update(entry.id,{month:e.target.value})}/><select className="me-select" aria-label="相册内容类型" value={entry.type} onChange={e=>update(entry.id,{type:e.target.value as AlbumEntry['type']})}><option value="text">文字</option><option value="image">图片</option><option value="video">视频封面</option></select></div><textarea className="me-textarea" rows={2} placeholder="文字内容" value={entry.content} onChange={e=>update(entry.id,{content:e.target.value})}/>{entry.type!=='text'&&<div className="album-edit-pictures">{entry.images.map((src,j)=><button key={j} title="删除图片" onClick={()=>update(entry.id,{images:entry.images.filter((_,k)=>k!==j)})}><img src={src} alt=""/>×</button>)}<label className="btn btn-outline btn-sm"><ImagePlus size={14}/>{entry.type==='video'?'上传视频封面':'添加图片'}<input type="file" accept="image/png,image/jpeg,image/webp,image/gif" multiple={entry.type==='image'} hidden onChange={async e=>{const files=Array.from(e.target.files||[]);e.target.value='';try{const existing=entry.type==='video'?[]:entry.images;const pics=await Promise.all(files.slice(0,entry.type==='video'?1:9-existing.length).map(readLocalPicture));update(entry.id,{images:[...existing,...pics]})}catch(error){onToast((error as Error).message)}}}/></label></div>}</div>)}</div>
}

function Thumbnail({entry}:{entry:AlbumEntry}) {
  const pictures=entry.images.slice(0,4)
  return <div className={'album-thumbnail count-'+pictures.length}>{pictures.map((src,i)=><img src={src} key={i} alt=""/>)}{!pictures.length&&(entry.type==='text'?<span><WechatText text={entry.content}/></span>:<Camera color="#d0d0d0" size={25}/>)}{entry.type==='video'&&<svg className="album-play" width="32" height="32" viewBox="0 0 36 36" fill="none"><circle cx="18" cy="18" r="16" stroke="white" strokeWidth="1.5"/><path d="m14 10 13 8-13 8z" fill="white"/></svg>}</div>
}

export function AlbumPreview({draft,onAdd,onSelect}:{draft:MomentProject;onAdd?:()=>void;onSelect?:(id:string)=>void}) {
  const entries=draft.entries||[],pinned=entries.filter(e=>e.pinned)
  const groups: {key:string;date:string;month:string;entries:AlbumEntry[]}[]=[]
  entries.forEach(e=>{const key=e.date+'|'+e.month;const last=groups.at(-1);if(last?.key===key)last.entries.push(e);else groups.push({key,date:e.date,month:e.month,entries:[e]})})
  return <div className="album-preview"><div className="album-cover" style={{backgroundColor:draft.coverColor,backgroundImage:draft.coverImage?`url(${draft.coverImage})`:undefined}}><div className="album-profile"><strong>{draft.author}</strong><span>{draft.avatar?<img src={draft.avatar} alt=""/>:draft.author.slice(0,1)}</span></div></div><p className="album-signature">{draft.signature}</p>{pinned.length>0&&<div className="album-pinned"><b>置顶</b><div>{pinned.slice(0,3).map(e=><button key={e.id} onClick={()=>onSelect?.(e.id)}><Thumbnail entry={e}/></button>)}</div><ChevronRight size={20}/></div>}<div className="album-timeline">{draft.albumMode==='self'&&<div className="album-date-group"><b>今天</b><button className="album-camera" aria-label="添加今天的朋友圈" onClick={onAdd}><Camera size={28} fill="#d5d5d5" color="#d5d5d5"/></button></div>}{groups.map((g,i)=><div className="album-date-group" key={g.key+i}><b>{g.date}<small>{g.month}</small></b><div className="album-day-entries">{g.entries.map(e=><button className={'album-post-row '+(e.type==='text'?'text-only':'')} key={e.id} onClick={()=>onSelect?.(e.id)}>{e.type!=='text'&&<Thumbnail entry={e}/>}<span><WechatText text={e.content}/></span>{e.images.length>1&&<small>共{e.images.length}张</small>}</button>)}</div></div>)}</div></div>
}
